import uuid from '../lang/uuid';

export default {
    TRIGGERS: 'THIRDMESSAGE_715B94309A3DB7F3E9FBA7F309880EEC',
    CALLBACKS: 'THIRDMESSAGE_CALLBACKS' + uuid(),
    TRUE_CALLBACKS: 'THIRDMESSAGE_TRUE_CALLBACKS' + uuid()
};
