export default {
    HTML_START: '<!DOCTYPE html><html><head><meta charset="UTF-8"></head>',
    HTML_END: '</html>',
    IE_HTML_SUFFIX: ''
    + '<script>'
    + 'var timer = setInterval('
    +     'function () {'
    +         'var arr = document.getElementsByTagName(\'script\');'
    +         'var links = document.getElementsByTagName(\'link\');'
    +         'var allLoaded = true;'
    +         'for (var i = 0; i < links.length; i++) {'
    +             'if (!/loaded|complete/.test(links[i].readyState)) {'
    +                 'allLoaded = false;'
    +             '}'
    +         '}'
    +         'for(var i = 0; i < arr.length; i++) {'
    +             'if (!/loaded|complete/.test(arr[i].readyState)) {'
    +                 'allLoaded = false;'
    +             '}'
    +         '}'
    +         'if (allLoaded) {'
    +             'clearInterval(timer);'
    +             'document.close();'
    +         '}'
    +     '},'
    +     '200'
    + ');'
    + '</script>'
};
